{{- define "templates.deployment" }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      "app.kubernetes.io/instance": "{{ .Release.Name }}"
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    # this should be configurable via values.yaml
    type: {{ .Values.strategy }}
  template:
    metadata:
      labels: 
        "app.kubernetes.io/instance": "{{ .Release.Name }}"
    spec:
      initContainers:
      {{ if .Values.securityContext }}
      securityContext:
        {{- with .Values.securityContext }}
          {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      volumes:
        {{- with .Values.extraVolumes }}
          {{ toYaml . | nindent 8 }}
        {{- end }}
      {{ if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: "{{ .Values.imagePullSecret }}"
      {{ end }}
      containers:
        - name: "{{ .Release.Name }}"
          image: "{{ .Values.image.repository }}"
          resources:
          {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.extraVolumeMounts }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
          ports:
            {{- with .Values.extraPorts }}
              {{ toYaml . | nindent 8 }}
            {{- end }}
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          env:
            {{- with .Values.extraEnvs }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.extraContainers }}
          {{ toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
